# -*- coding: utf-8 -*-
"""Validation_Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rn1rf3aE794y7BIY9pp7O8ZZqCTMG6oN
"""

# Q3(a) Automated Data Validation Script

import pandas as pd

# Load dataset (change file name if needed)
df = pd.read_csv("TelcoChurn_Analytics.csv")

# 1. Missing Values Check
print("=== Missing Values Check ===")
missing_values = df.isnull().sum()
print(missing_values)

# 2. Duplicate Rows Check
print("\n=== Duplicate Rows Check ===")
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

# 3. Data Types Check
print("\n=== Data Types Check ===")
print(df.dtypes)

print("\n=== Data Validation Completed ===")