# -*- coding: utf-8 -*-
"""model_SMOTE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OotqODV-SGbz4V44kHT__u2n47023jyk
"""

# 1. IMPORTS
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
from imblearn.over_sampling import SMOTE

# 2. LOAD DATA
df = pd.read_csv("TelcoChurn_Analytics.csv")

# 3. DATA CLEANING
df = df.copy()

# Handle missing values
df["Total_Charges"] = df["Total_Charges"].fillna(df["Total_Charges"].median())

# Feature engineering
df["Avg_Charge_Per_Month"] = df["Total_Charges"] / df["Tenure_Months"]
df["Avg_Charge_Per_Month"] = df["Avg_Charge_Per_Month"].fillna(
    df["Avg_Charge_Per_Month"].median()
)

# Encode target
df["Churn"] = df["Churn"].map({"No": 0, "Yes": 1})
df = df.dropna(subset=["Churn"])
df["Churn"] = df["Churn"].astype(int)

# Remove ID column
df = df.drop(columns=["Customer_ID"], errors="ignore")

# One-hot encoding
df = pd.get_dummies(df, drop_first=True)

# 4. FEATURE SELECTION
X = df[['Monthly_Charges', 'Total_Charges', 'Tenure_Months',
        'Support_Tickets_Count', 'Contract_Type_Two Year',
        'Internet_Service_Fiber']]

y = df["Churn"]

# 5. TRAIN-TEST SPLIT
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# 6. BASE MODEL (LOGISTIC REGRESSION)
lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("BASE MODEL RESULTS")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

# 7. SMOTE (IMPROVED MODEL)
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# 8. IMPROVED MODEL
model_smote = LogisticRegression(max_iter=1000, random_state=42)
model_smote.fit(X_train_res, y_train_res)

y_pred_smote = model_smote.predict(X_test)

print("\nIMPROVED MODEL (SMOTE)")
print("Accuracy:", accuracy_score(y_test, y_pred_smote))
print(classification_report(y_test, y_pred_smote))